fix fshealthtest

diff --git a/utils/fshealthtest b/utils/fshealthtest
--- a/utils/fshealthtest
+++ b/utils/fshealthtest
@@ -36,9 +36,25 @@ shift $((OPTIND - 1))
 
 [ $# -eq 1 ] || usage
 fsroot=$1
+
+# set -e means exit immediately if a command exits with a non-zero status.
+# With this, [ command ] below won't exit when command fails.
+
 set -e
 
 # phase 1: check for degraded or unavailable file systems
+#
+# Linux example:
+#
+# # mount | grep -w sbb5_pool0
+# sbb5_pool0 on /sbb5_pool0 type zfs (rw,relatime,xattr,noacl)
+#
+# FreeBSD  example:
+#
+# # mount | grep -w arc_sliod/0
+# sense1_pool0 on /arc_sliod/0 (zfs, local, noatime, nfsv4acls)
+#
+
 set -- $(mount | grep -w "$fsroot")
 if [ x"$4" = x"type" ]; then
 	# $1            $2 $3             $4   $5
@@ -54,13 +70,13 @@ fi
 case $fstype in
 zfs)	pool=$1
         #
-        # We used to looking for ONLINE/DEGRADED in specific
+        # We used to look for ONLINE/DEGRADED in specific
         # column in the zpool list output with awk. However,
         # FreeBSD and Linux have different formats. So grep
         # is used now.
         #
 	stat=$(zpool list -H $pool | grep ONLINE)
-        if [ $stat -ne 0 ]
+	if [ $? -ne 0 ]
         then
             exit 1
         fi
